name: Build & Deploy to Fly.io

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY_IMAGE: ghcr.io/Vlad07062002Vlad/gotovo-bot:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push image
        run: docker buildx build --platform linux/amd64 -t "$REGISTRY_IMAGE" --push .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1
      - name: Deploy image to Fly
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          FLY_APP: ${{ secrets.FLY_APP }}
          REGISTRY_IMAGE: ${{ env.REGISTRY_IMAGE }}
        run: |
          flyctl deploy --image "$REGISTRY_IMAGE" -a "$FLY_APP" --wait-timeout 600
