# fly.toml
app = "gotovo-bot"
primary_region = "waw"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = "15s"
    timeout = "10s"
    grace_period = "5s"
    method = "GET"
    path = "/"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"

# маунт для process-group 'app'
[[mounts]]
  source = "data"
  destination = "/data"
  processes = ["app"]
