name: Deploy to Fly.io
on:
  push: { branches: [ main ] }
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    env: { APP: ${{ secrets.FLY_APP }} }
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@v1
      - name: Sanity
        run: |
          test -n "${APP}" || (echo "::error::Set secrets.FLY_APP"; exit 1)
          echo "Deploying to ${APP}"
      - name: Deploy (remote builder)
        env: { FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }} }
        run: flyctl deploy --remote-only -a "${APP}" --wait-timeout 600
      - name: Status
        if: always()
        env: { FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }} }
        run: |
          flyctl status -a "${APP}" || true
          flyctl releases -a "${APP}" || true
          flyctl machines list --app "${APP}" || true
      - name: Tail logs on failure
        if: failure()
        env: { FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }} }
        run: flyctl logs -a "${APP}" --max-lines 200 || true

