name: Deploy to Fly.io

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      APP: ${{ secrets.FLY_APP }}  # например: "gotovo-bot"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@v1

      - name: Check required secrets
        run: |
          if [ -z "${FLY_API_TOKEN}" ]; then
            echo "::error::Missing FLY_API_TOKEN secret"
            exit 1
          fi
          if [ -z "${APP}" ]; then
            echo "::error::Missing FLY_APP secret"
            exit 1
          fi

      - name: Deploy to Fly.io (remote builder)
        run: flyctl deploy --remote-only --app "$APP"
